kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: mbigras/app:latest
